_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 103
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.10.16
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
input_shape:
    value:
        - 3
        - 32
        - 32
learning_rate:
    value: 0.0002
num_classes:
    value: 10
